### ISSUE TITLE
Python Service Scaling Issue

### ISSUE THREAD

**Issue by SansBailmare** [airavata-courses/dexlab#31]

**Comment by sbmthakur** [comment]
```
Traceback (most recent call last):
  File "/venv/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/venv/lib/python3.8/socketserver.py", line 697, in process_request
    t.start()
  File "/venv/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap,

```
